semantic:
  repositories:
    payment-service:
      url: file:///uat-git/payment-service.git
      default-branch: main
    order-service:
      url: file:///uat-git/order-service.git
      default-branch: main
    video-service:
      url: file:///uat-git/video-service.git
      default-branch: main
