semantic:
  repositories:
    payment-service:
      mode: LOCAL_FIXTURE
      display-name: Payment Service
      path: /fixtures/payment-service
    order-service:
      mode: LOCAL_FIXTURE
      display-name: Order Service
      path: /fixtures/order-service
    video-service:
      mode: LOCAL_FIXTURE
      display-name: Video Service
      path: /fixtures/video-service
